# Generated by Django 3.1.5 on 2021-01-27 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('director', models.CharField(max_length=100, unique=True)),
                ('year_released', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('country', models.CharField(max_length=50, unique=True)),
                ('run_time', models.DurationField()),
                ('plot', models.CharField(max_length=600)),
                ('genre', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=500)),
                ('distributor', models.CharField(max_length=50)),
                ('film_format', models.CharField(max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
