# Generated by Django 3.1.5 on 2021-01-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('films', '0004_auto_20210127_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='section',
            field=models.ManyToManyField(related_name='films', to='sections.Section'),
        ),
    ]
