# Generated by Django 3.1.5 on 2021-01-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0005_film_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posted_films', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
