# Generated by Django 3.1.5 on 2021-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('films', '0008_auto_20210129_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='films', to='sections.Section'),
        ),
    ]
