# Generated by Django 3.1.5 on 2021-01-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_slots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='date',
        ),
    ]
