# Generated by Django 3.1.5 on 2021-01-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210127_1253'),
        ('scheduling_slots', '0003_slot_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='film',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='films.film'),
        ),
    ]
